[fmt]
line_length = 120

[profile.default]
bytecode_hash = "none"
optimizer_runs = 1000000
solc = "0.8.17"
fs_permissions = [{ access = "read-write", path = "./logs/"}]
libs = ["node_modules", "lib"]

[profile.intense]
fuzz_runs = 10000
